program/app/config/routes.rb
Rails.application.routes.draw do
  #resources :resources
  #resources :zones
  resources :cities

  
  root 'cities#index'
  get '/contact_us', to: 'static_pages#contact_us'
  #get 'static_pages#contact_us'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

program/app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

program/app/app/models/city.rb
class City < ApplicationRecord

    def display_time standard_format
        if standard_format
            time.strftime("%H:%M")
        else 
            if (time.hour > 12)
                temp_time = time
                temp_time = time - 12.hour
                temp_time.strftime("%H:%M PM")
            else
                time.strftime("%H:%M AM")
            end
        end
    end
            

    def make_default
        update_attribute(:default, true)
    end

    def remove_default
        update_attribute(:default, false)
    end

    def update_time
        update_attribute(:time, Time.current)
        update_attribute(:time, offset.hour.from_now)
    end

    def update_time_status
        if (time.hour >= 9 and time.hour < 18)
            update_attribute(:time_status, "Buisness Time") 
        elsif (time.hour >= 18 and time.hour < 20)
            update_attribute(:time_status, "Buisness Overtime") 
        elsif (time.hour >= 8 and time.hour < 9 or time.hour >= 20 and time.hour < 23)
            update_attribute(:time_status, "Personal Time")
        elsif (time.hour >= 23 or time.hour < 8)
            update_attribute(:time_status, "Sleeping Time")
        end
    end

    def update_day_status default_city
        day_difference = time.day - default_city.time.day
        if (day_difference == 0)
            update_attribute(:day_status, "today") 
        elsif (day_difference < 0)
            update_attribute(:day_status, "yesterday")
        elsif (day_difference > 0)
            update_attribute(:day_status, "tommorow")
        end
    end

    def update_time_difference default_city
        time_difference = time - default_city.time
        time_difference /= 60
        time_difference /= 60
        update_attribute(:time_difference, time_difference.round)
    end

end

program/app/app/models/resource.rb
class Resource < ApplicationRecord
end

program/app/app/models/zone.rb
class Zone < ApplicationRecord
end

program/app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

program/app/app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :find_default
  before_action :update_time
  before_action :set_city, only: [:show, :edit, :update, :destroy]


  # GET /cities
  # GET /cities.json
  def index
    @cities = City.all
    @enable_standard_format = true
    @selectable_cities = []
    @cities.each do |city|
      @selectable_cities << [city.name, city.id]
    end

    if params[:new_default].present?
      City.find_by(id: @default.id).remove_default
      City.find_by(id: params[:new_default]).make_default
      redirect_to root_url
    end

    if params[:change_time_format] == "1"
      @enable_standard_format = false
    end

    if params[:change_time_format] == "0"
      @enable_standard_format = true
    end

  end

  # GET /cities/new
  def new
    @city = City.new
  end

  # POST /cities
  # POST /cities.json
  def create

    if params[:search].present?
      @search_result = Resource.find_by(city_name: params[:search].downcase)
      if (!@search_result.nil?)
        @city = City.new(
          :name => @search_result.city_name,
          :offset => @search_result.offset,
          :default => false,
          :time => Time.current,
          :time_status => "",
          :time_difference => 0.0
        )
        @city.save
        redirect_to root_url
      else
        redirect_to root_url
      end
    end
  end

  # DELETE /cities/1
  # DELETE /cities/1.json
  def destroy
    @city.destroy
    respond_to do |format|
      format.html { redirect_to cities_url, notice: 'City was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def find_default
      City.all.each do |city|
        if city.default
          @default = city
        end
      end
    end

    def set_city
      @city = City.find(params[:id])
    end

    def update_time
      City.all.each do |city|
        city.update_time
        city.update_time_status
        city.update_day_status @default
        city.update_time_difference @default
      end
    end

    # Only allow a list of trusted parameters through.
    def city_params
      params.permit(:name, :time, :offset, :default, :time_status, :time_difference)
    end
end

program/app/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    def contact_us

    end  
end

program/app/app/helpers/application_helper.rb
module ApplicationHelper
end

program/app/app/helpers/cities_helper.rb
module CitiesHelper

end

program/app/app/helpers/hello_helper.rb
module HelloHelper
end

program/app/app/helpers/index_helper.rb
module IndexHelper
end

program/app/app/helpers/resources_helper.rb
module ResourcesHelper
end

program/app/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

program/app/app/helpers/zones_helper.rb
module ZonesHelper

end

program/app/app/views/application/_footer.html.erb
<footer class="footer">
    <div class = "container">
        
        <div id = "footer-images">
            <p>Clock+ - s3784828@student.rmit.edu.au, highest level attemped = distinction </p>

            <%= link_to image_tag(url_for("twitter.png"), :size => "50x50"),  "https://twitter.com/explore" %>
  
            <%= link_to image_tag(url_for("linkedin.png"), :size => "50x50"),  "https://au.linkedin.com/" %>

            <%= link_to image_tag(url_for("facebook.png"), :size => "50x50"),  "https://www.facebook.com/" %>

        </div>
    </div>
</footer>

program/app/app/views/application/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
        <ul class="nav navbar-nav navbar-centre">
          <li><%= link_to "Clock+", root_path, id: "logo" %></li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Show Case", root_path %></li>
          <li><%= link_to "Contact Us", contact_us_path %></li>
        </ul>
    </div>
</header>

program/app/app/views/cities/_glossary.html.erb
<ul>
    <ul> <p> <%= image_tag("green.png") %> Buisness Time </p> </ul>
    <ul> <p> <%= image_tag("orange.png") %> Buisness Overtime </p> </ul>
    <ul> <p> <%= image_tag("red.png") %> Personal Time </p> </ul>
    <ul> <p> <%= image_tag("sleepy.png") %> Sleep Time </p> </ul>
</ul>

program/app/app/views/cities/_search_city.html.erb
<%= form_tag(cities_path, :method => 'post', :action => 'create_via_search') do %>

    <%= text_field_tag :search %>

    <%= submit_tag "Add City" %>
    
<% end %>

program/app/app/views/cities/_select_city.html.erb
<%= form_tag(cities_path, :method => "get", :action => "index") do %>
    <%= select_tag :new_default, options_for_select(possible_options) %>
    <%= submit_tag 'Change default' %>
<% end %>

program/app/app/views/cities/_select_time_format.html.erb
<%= form_tag(cities_path, :method => "get", :action => "index") do %>
    <%= check_box_tag :change_time_format %>
    <%= submit_tag "Change time settings" %>
<% end %>

program/app/app/views/cities/index.html.erb
  <h1> Clock+ </h1>
  <h4> By Tristan Macaulay s3784828 - highest level attempted = distinction </h4>
 
  <% if !@default.nil? %>
    <Table style = "width: 50%; margin-bottom: 0px;" cellspacing = "0" cellpadding = "0">
      <colgroup>
        <col span="1" style="width: 40%">
        <col span="1" style="width: 35%">
        <col span="1" style="width: 25%">
      </colgroup>

          <tr>
            <td>
              <%= render 'select_city', possible_options: @selectable_cities %>
            </td>
            <td>
              <span><h2><%= @default.name.upcase %></h2></span>
            </td>
            <td><h3><%= @default.display_time @enable_standard_format %></h3></td>
          </tr>

    </table>
  <% end %>

  <Table style = "width: 50%; margin-bottom: 30px;" cellspacing = "0" cellpadding = "0">

    <colgroup>
      <col span="1" style="width: 50%;">
      <col span="1" style="width: 30%">
      <col span="1" style="width: 10%">
      <col span="1" style="width: 10%">
    </colgroup>

    <% @cities.each do |city| %>
    
      <tr>
        <% if !city.default %>
          <td>
            <span><h2><%= city.name.upcase %></h2></span>
            <span><h5><%= city.day_status %></h5></span>
          </td>
          <td>
            <span><h3><%= city.display_time @enable_standard_format%></h3></span>
            <span><h5><%= city.time_difference.to_s %><h5></span>
          </td>
          <td> 
            <% if city.time_status == "Buisness Time"%>
              <%= image_tag(url_for("green.png")) %>
            <% elsif city.time_status == "Buisness Overtime" %>
              <%= image_tag(url_for("orange.png")) %>
            <% elsif city.time_status == "Personal Time" %>
              <%= image_tag(url_for("red.png")) %>
            <% elsif city.time_status == "Sleeping Time" %>
              <%= image_tag(url_for("sleepy.png")) %>
            <% end %>
          <td>
          <td><span><%= link_to image_tag(url_for("delete.png")), city, method: :delete, data: { confirm: 'Are you sure?' } %></span></td>
        <% end %>
      </tr>
    <% end %>

    <h4> <%= link_to image_tag("plus.png"), new_city_path %> Add a city </h4>

  </table>

  

program/app/app/views/cities/new.html.erb
<div id = "new-city">
    <%= render "search_city" %>

    <h4> <%= link_to image_tag(url_for("goback.png")), cities_path %> Go back </h4>
</div>

program/app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

program/app/app/views/layouts/cities.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <%= render 'header' %>
  <div class = container>
    <body>
        <div id = "side-content-left">
            <%= render "glossary"%>
        </div>

        <div id = "side-content-right">
            <%= render "select_time_format", city: City %>
        </div>

        <div id = "main-content">
            <%= yield %>
        </div>
    </body>
  </div>
  <%= render 'footer'%>
</html>

program/app/app/views/static_pages/contact_us.html.erb
<p> Student email = s3784828@student.rmit.edu.au </p>